// Canonical source of truth for the Five-Day Split Tracker workout plan.
// Do not change exercise names, sets, reps, or starting weights here —
// the client never hardcodes this data, it always reads it from the API.

export const EXERCISES = {
  'incline-db-press': {
    name: 'Incline Dumbbell Press',
    sets: 3,
    repsLabel: '6-8 reps',
    weightLabel: '10 kg',
    unit: 'kg',
    startingWeight: 10,
    isBodyweight: false,
    isVariable: false,
    restSeconds: 90,
  },
  'weighted-lat-pulldown': {
    name: 'Weighted Lat Pulldown',
    sets: 3,
    repsLabel: '6-8 reps',
    weightLabel: '30 kg',
    unit: 'kg',
    startingWeight: 30,
    isBodyweight: false,
    isVariable: false,
    restSeconds: 90,
  },
  'goblet-squat': {
    name: 'Goblet Squat',
    sets: 3,
    repsLabel: '6-8 reps',
    weightLabel: '12-15 kg',
    unit: 'kg',
    startingWeight: 12,
    isBodyweight: false,
    isVariable: false,
    restSeconds: 90,
  },
  'romanian-deadlift': {
    name: 'Romanian Deadlift',
    sets: 3,
    repsLabel: '6-8 reps',
    weightLabel: '2 x 8-10 kg dumbbells',
    unit: 'kg',
    startingWeight: 8,
    isBodyweight: false,
    isVariable: false,
    restSeconds: 90,
  },
  'pendlay-row': {
    name: 'Pendlay Row',
    sets: 2,
    repsLabel: '8-10 reps',
    weightLabel: '20-25 kg',
    unit: 'kg',
    startingWeight: 20,
    isBodyweight: false,
    isVariable: false,
    restSeconds: 75,
  },
  'db-lateral-raise': {
    name: 'Dumbbell Lateral Raise',
    sets: 2,
    repsLabel: '8-10 reps',
    weightLabel: '2-3 kg',
    unit: 'kg',
    startingWeight: 2,
    isBodyweight: false,
    isVariable: false,
    restSeconds: 60,
  },
  'seated-cable-fly': {
    name: 'Seated Cable Fly',
    sets: 2,
    repsLabel: '10-12 reps',
    weightLabel: 'Light-moderate weight',
    unit: 'kg',
    startingWeight: null,
    isBodyweight: false,
    isVariable: true,
    restSeconds: 60,
  },
  'leg-extension-machine': {
    name: 'Leg Extension Machine',
    sets: 2,
    repsLabel: '8-10 reps',
    weightLabel: 'Light-moderate weight',
    unit: 'kg',
    startingWeight: null,
    isBodyweight: false,
    isVariable: true,
    restSeconds: 60,
  },
  'preacher-curl': {
    name: 'Preacher Curl',
    sets: 2,
    repsLabel: '8-10 reps',
    weightLabel: '4-6 kg',
    unit: 'kg',
    startingWeight: 4,
    isBodyweight: false,
    isVariable: false,
    restSeconds: 60,
  },
  'lying-leg-curl-machine': {
    name: 'Lying Leg Curl Machine',
    sets: 2,
    repsLabel: '6-8 reps',
    weightLabel: 'Light-moderate weight',
    unit: 'kg',
    startingWeight: null,
    isBodyweight: false,
    isVariable: true,
    restSeconds: 60,
  },
  'cable-overhead-triceps-ext': {
    name: 'Cable Overhead Triceps Extension',
    sets: 2,
    repsLabel: '8-10 reps',
    weightLabel: 'Light weight',
    unit: 'kg',
    startingWeight: null,
    isBodyweight: false,
    isVariable: true,
    restSeconds: 60,
  },
  'sumo-squat-walk': {
    name: 'Sumo Squat Walk',
    sets: 2,
    repsLabel: '10 steps each direction',
    weightLabel: 'Bodyweight',
    unit: null,
    startingWeight: null,
    isBodyweight: true,
    isVariable: false,
    restSeconds: 45,
  },
  'standing-calf-raise': {
    name: 'Standing Calf Raise',
    sets: 3,
    repsLabel: '8-10 reps',
    weightLabel: 'Bodyweight',
    unit: null,
    startingWeight: null,
    isBodyweight: true,
    isVariable: false,
    restSeconds: 60,
  },
};

// Order matters — this is the exact order exercises appear within each day.
export const DAY_PLAN = {
  1: ['incline-db-press', 'weighted-lat-pulldown', 'goblet-squat'],
  2: ['romanian-deadlift', 'pendlay-row', 'db-lateral-raise'],
  3: ['seated-cable-fly', 'leg-extension-machine', 'preacher-curl'],
  4: ['lying-leg-curl-machine', 'cable-overhead-triceps-ext', 'sumo-squat-walk'],
  5: ['standing-calf-raise', 'goblet-squat', 'romanian-deadlift'],
};

export const CARDIO = {
  name: 'Incline Treadmill',
  durationLabel: '20 minutes',
  detailLabel: '10-12% incline, 3.5-4 km/h',
};

export const DAYS = [1, 2, 3, 4, 5];
